### PR TITLE
Adding the basics

### PR DESCRIPTION
**Pull request by trezy**
This PR adds a lot of basic structure to the web app.

### CODE REVIEW

**Comment by Marenthyu** [comment]
The yarn cache .zip file is included here - is that intended? From past knowledge, such binary files should not be in a hit repo. Update .gitignore potentially?

**Comment by trezy** [comment]
> The yarn cache .zip file is included here - is that intended? From past knowledge, such binary files should not be in a hit repo. Update .gitignore potentially?

This is intentional. Zero Installs are a new thing with Yarn 2. [See their docs](https://next.yarnpkg.com/features/zero-installs) for more info.

**Comment by Marenthyu** [comment]
SGTM, then - It still feels a bit wrong to store a binary file in the repo directly - would it be possible to store it in LFS instead? (Note that i am wholly unfamiliar with that as well and am just trying to stick to old known good practices.)

**Comment by trezy** [comment]
> SGTM, then - It still feels a bit wrong to store a binary file in the repo directly - would it be possible to store it in LFS instead? (Note that i am wholly unfamiliar with that as well and am just trying to stick to old known good practices.)

The thing is that because Yarn 2 stores all of its modules in zip archives, they're already compressed. For example, the entire `sass` archive is ~0.5MB. The total size of the Yarn cache for the project is only ~70MB right now. LFS is way overkill for such small stuff.

The other nice thing about Zero-Installs is that — also due to the fact that Yarn 2 stores it's cache in zip archives — only 3 files will be changed with a package add/upgrade/remove: `package.json`, `yarn.lock`, and the archive for the package itself.

**Pull request merged**
